cache:
  paths:
  - Example/Pods
before_script:
  - bundle install
  - bundle exec pod install --project-directory=Example
after_script:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
stages:
  - build
  - test
  - deploy
deploy_cocoapods:
  stage: deploy
  script:
    - bundle exec fastlane push
  environment: cocoapods
  when: manual
  only:
    - master
  tags:
  - xcode_8
  - ruby_2-3
  - bundler
build:
  stage: build
  script:
    - bundle exec fastlane build
  tags:
  - xcode_8
  - ruby_2-3
  - bundler
test:
  stage: test
  script:
    - bundle exec fastlane test
  tags:
  - xcode_8
  - ruby_2-3
  - bundler
  artifacts:
    paths:
    - fastlane/**/*.xml
    - fastlane/**/*.junit
    - fastlane/**/*.html